version: '3'
networks:
  bridge: 
    external: 
      name: cloud
services: 
  laravel: 
#    image: panshx/php-fpm-56
    image: panshx/laravel
    container_name: laravel
    hostname: laravel
    command: 
      - /bin/sh
      - -c 
      - |
          nginx -c /etc/nginx/nginx.conf
          php-fpm -D -y /etc/php5/php-fpm.conf
          tail -f /dev/null
#    tty: true
    environment: 
      NGINX_HOME: /usr/local/nginx
    networks: 
#      - bridge
      bridge: 
        ipv4_address: 172.18.88.29
#        ipv4_address: 172.16.18.29
#    ports: 
#      - "80:80"
    volumes: 
#      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./conf/conf.d:/etc/nginx/conf.d
      - ./nginx:/etc/nginx
      - ./php:/etc/php5
#      - ./data:/usr/local/nginx/html
      - ./5.3/blog:/usr/local/laravel
      - ./logs:/usr/local/nginx
      - ./php-5.6.40:/usr/local/src
      