version: '3'
networks:
  bridge: 
    external: 
      name: multihost
services: 
  ngx021: 
    image: nginx:1.15-alpine
    container_name: ngx021
    hostname: ngx021
#    tty: true
    environment: 
      NGINX_HOME: /usr/local/nginx
#    extra_hosts: 
#      - ngx021
#      ngx021: 172.16.18.21
    networks: 
      - bridge
#      bridge: 
#        ipv4_address: 172.16.18.21
#        ipv4_address: 172.17.2.21
#    ports: 
#      - "80:80"
    volumes: 
      - ./021/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./021/conf/conf.d:/etc/nginx/conf.d
      - ./021/data:/usr/local/nginx
      - ./021/logs:/var/log/nginx
  ngx022: 
    image: nginx:1.15-alpine
    container_name: ngx022
    hostname: ngx022
#    tty: true
    environment: 
      NGINX_HOME: /usr/local/nginx
#    extra_hosts: 
#      - ngx021
#      ngx021: 172.16.18.21
    networks: 
      - bridge
#      bridge: 
#        ipv4_address: 172.16.18.22
#        ipv4_address: 172.17.2.22
#    ports: 
#      - "443:443"
    volumes: 
      - ./022/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./022/conf/conf.d:/etc/nginx/conf.d
      - ./022/data:/usr/local/nginx
      - ./022/logs:/var/log/nginx
  ngx023: 
    image: nginx:1.15-alpine
    container_name: ngx023
    hostname: ngx023
#    tty: true
    environment: 
      NGINX_HOME: /usr/local/nginx
#    extra_hosts: 
#      - ngx021
#      ngx021: 172.16.18.21
    networks: 
      - bridge
#      bridge: 
#        ipv4_address: 172.16.18.23
#        ipv4_address: 172.17.2.23
#    ports: 
#      - "443:443"
    volumes: 
      - ./023/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./023/conf/conf.d:/etc/nginx/conf.d
      - ./023/data:/usr/local/nginx
      - ./023/logs:/var/log/nginx
      
      