# https://github.com/arc-ts/keepalived/blob/master/Dockerfile    
FROM alpine

RUN apk add --no-cache \
    bash       \
    curl       \
    ipvsadm    \
    iproute2   \
    keepalived 

# CMD ["./init.sh"]

