version: '3'
networks:
  bridge: 
    external: 
      name: cloud
services: 
  redis50: 
    image: redis:5-alpine 
    container_name: redis50 
    hostname: redis50 
    restart: always
    networks: 
      - bridge
    ports: 
      - "6379:6379" 
    volumes: 
#      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data:/data
      - ./logs:/usr/local/redis/logs 
    
