version: '3'
networks:
  bridge: 
    external: 
      name: hadoop
services: 
  redis-cluster-70: 
    image: redis:5-alpine 
    container_name: redis-cluster-70 
    hostname: redis-cluster-70 
    working_dir: /usr/local/redis
    command: redis-server /usr/local/redis/conf/redis.conf
    networks: 
      bridge: 
        ipv4_address: 172.16.18.70
#      - bridge
#    ports: 
#      - "7000:7000" 
    volumes: 
      - ./70/conf/redis.conf:/usr/local/redis/conf/redis.conf
      - ./70/data:/usr/local/redis/data
      - ./70/logs:/usr/local/redis/logs 
  redis-cluster-71: 
    image: redis:5-alpine 
    container_name: redis-cluster-71
    hostname: redis-cluster-71 
    working_dir: /usr/local/redis
    command: redis-server /usr/local/redis/conf/redis.conf
    networks: 
      bridge: 
        ipv4_address: 172.16.18.71
#      - bridge
#    ports: 
#      - "7000:7000" 
    volumes: 
      - ./71/conf/redis.conf:/usr/local/redis/conf/redis.conf
      - ./71/data:/usr/local/redis/data
      - ./71/logs:/usr/local/redis/logs 
  redis-cluster-72: 
    image: redis:5-alpine 
    container_name: redis-cluster-72 
    hostname: redis-cluster-72 
    working_dir: /usr/local/redis
    command: redis-server /usr/local/redis/conf/redis.conf
    networks: 
      bridge: 
        ipv4_address: 172.16.18.72
#      - bridge
#    ports: 
#      - "7000:7000" 
    volumes: 
      - ./72/conf/redis.conf:/usr/local/redis/conf/redis.conf
      - ./72/data:/usr/local/redis/data
      - ./72/logs:/usr/local/redis/logs 
  redis-cluster-80: 
    image: redis:5-alpine 
    container_name: redis-cluster-80 
    hostname: redis-cluster-80 
    working_dir: /usr/local/redis
    command: redis-server /usr/local/redis/conf/redis.conf
    networks: 
      bridge: 
        ipv4_address: 172.16.18.80
#      - bridge
#    ports: 
#      - "7000:7000" 
    volumes: 
      - ./80/conf/redis.conf:/usr/local/redis/conf/redis.conf
      - ./80/data:/usr/local/redis/data
      - ./80/logs:/usr/local/redis/logs 
  redis-cluster-81: 
    image: redis:5-alpine 
    container_name: redis-cluster-81
    hostname: redis-cluster-81 
    working_dir: /usr/local/redis
    command: redis-server /usr/local/redis/conf/redis.conf
    networks: 
      bridge: 
        ipv4_address: 172.16.18.81
#      - bridge
#    ports: 
#      - "7000:7000" 
    volumes: 
      - ./81/conf/redis.conf:/usr/local/redis/conf/redis.conf
      - ./81/data:/usr/local/redis/data
      - ./81/logs:/usr/local/redis/logs 
  redis-cluster-82: 
    image: redis:5-alpine 
    container_name: redis-cluster-82 
    hostname: redis-cluster-82 
    working_dir: /usr/local/redis
    command: redis-server /usr/local/redis/conf/redis.conf
    networks: 
      bridge: 
        ipv4_address: 172.16.18.82
#      - bridge
#    ports: 
#      - "7000:7000" 
    volumes: 
      - ./82/conf/redis.conf:/usr/local/redis/conf/redis.conf
      - ./82/data:/usr/local/redis/data
      - ./82/logs:/usr/local/redis/logs 
    
